# Generated by Django 5.0.2 on 2024-03-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_alter_favoriteuser_favorite_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteuser',
            options={'verbose_name': 'favorite user', 'verbose_name_plural': 'favorite users'},
        ),
    ]
