# Generated by Django 5.0.2 on 2024-06-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0007_userprofilereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_options',
            field=models.JSONField(blank=True, default=list, verbose_name='contact options'),
        ),
    ]
