# Generated by Django 5.0.2 on 2024-09-23 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0011_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteuser',
            options={'verbose_name': 'mėgstamas naudotojas', 'verbose_name_plural': 'mėgstami naudotojai'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profilis', 'verbose_name_plural': 'profiliai'},
        ),
        migrations.AlterModelOptions(
            name='userprofilereview',
            options={'verbose_name': 'profilio apžvalga', 'verbose_name_plural': 'profilio apžvalgos'},
        ),
        migrations.AlterField(
            model_name='favoriteuser',
            name='favorite_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to=settings.AUTH_USER_MODEL, verbose_name='mėgstamas naudotojas'),
        ),
        migrations.AlterField(
            model_name='favoriteuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_users', to=settings.AUTH_USER_MODEL, verbose_name='patinka'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='miestas'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='kontaktai'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_pictures/', verbose_name='nuotrauka'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='naudotojas'),
        ),
        migrations.AlterField(
            model_name='userprofilereview',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.userprofile', verbose_name='peržiūrėtas profilis'),
        ),
        migrations.AlterField(
            model_name='userprofilereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='apžvalga pateikta'),
        ),
    ]
