# Generated by Django 5.0.2 on 2024-04-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_color_listing_quality_listing_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(db_index=True, max_length=100, verbose_name='color'),
        ),
    ]
