# Generated by Django 5.0.2 on 2024-05-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Grey'), ('silver', 'Silver'), ('gold', 'Golden'), ('beige', 'Beige'), ('brown', 'Brown'), ('dark_blue', 'Dark Blue'), ('blue', 'Blue'), ('light_blue', 'Light Blue'), ('cyan', 'Blue'), ('green', 'Green'), ('khaki', 'khaki'), ('yellow', 'Yellow'), ('mustard', 'Mustard'), ('orange', 'Orange'), ('coral', 'Coral'), ('red', 'Red'), ('burgundy', 'Burgundy'), ('light_pink', 'Light Pink'), ('pink', 'Pink'), ('bright_pink', 'Bright Pink'), ('purple', 'Purple'), ('lavender', 'Lavender'), ('mint', 'Mint'), ('turquoise', 'Turquoise'), ('maroon', 'Burgundy'), ('peach', 'Peach'), ('ivory', 'Ivory'), ('champagne', 'Champagne'), ('rose_gold', 'Rose Gold'), ('bronze', 'Bronze'), ('blush', 'Pink'), ('cobalt_blue', 'Cobalt Blue'), ('emerald', 'Emerald'), ('magenta', 'Purple'), ('fuchsia', 'Fuchsia')], db_index=True, default=None, max_length=20, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quality',
            field=models.CharField(choices=[('newwithtags', 'New with tags'), ('newwithouttags', 'New without tags'), ('great', 'Great'), ('good', 'Good'), ('worn', 'Worn')], default='good', max_length=20),
        ),
    ]
