# Generated by Django 5.0.2 on 2024-06-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listing_picture_1_listing_picture_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is for sale'),
        ),
    ]
