# Generated by Django 5.0.2 on 2024-09-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_waitlistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='vardas'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='vardas'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='vardas'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='vardas'),
        ),
    ]
