# Generated by Django 5.0.2 on 2024-09-23 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_alter_brand_name_alter_category_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'prekinis ženklas', 'verbose_name_plural': 'prekiniai ženklai'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategorija', 'verbose_name_plural': 'kategorijos'},
        ),
        migrations.AlterModelOptions(
            name='favoritelisting',
            options={'verbose_name': 'mėgstamiausias skelbimas', 'verbose_name_plural': 'mėgstamiausi skelbimai'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['is_available', 'created_at'], 'verbose_name': 'skelbimas', 'verbose_name_plural': 'skelbimai'},
        ),
        migrations.AlterModelOptions(
            name='listingreview',
            options={'verbose_name': 'skelbimo apžvalga', 'verbose_name_plural': 'skelbimo apžvalgos'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'žyma', 'verbose_name_plural': 'žymos'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='vardas'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='vardas'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='trumpinys'),
        ),
        migrations.AlterField(
            model_name='favoritelisting',
            name='favorite_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_listings', to='listings.listing', verbose_name='mėgstamiausias skelbimas'),
        ),
        migrations.AlterField(
            model_name='favoritelisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_listings', to=settings.AUTH_USER_MODEL, verbose_name='pamėgta'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing', to='listings.category', verbose_name='kategorija'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(choices=[('black', 'Juoda'), ('white', 'Balta'), ('gray', 'Pilka'), ('silver', 'Sidabrinė'), ('gold', 'Auksinė'), ('beige', 'Smėlio spalva'), ('brown', 'Ruda'), ('dark_blue', 'Tamsiai mėlyna'), ('blue', 'Mėlyna'), ('light_blue', 'Šviesiai mėlyna'), ('cyan', 'Mėlyna'), ('green', 'Žalia'), ('khaki', 'Chaki'), ('yellow', 'Geltona'), ('mustard', 'Garstyčių spalva'), ('orange', 'Oranžinė'), ('coral', 'Koralo spalva'), ('red', 'Raudona'), ('burgundy', 'Bordo'), ('light_pink', 'Šviesiai rožinė'), ('pink', 'Rožinė'), ('bright_pink', 'Ryškiai rožinė'), ('purple', 'Violetinė'), ('lavender', 'Levandų spalva'), ('mint', 'Mėtinė'), ('turquoise', 'Turkio spalva'), ('maroon', 'Bordo'), ('peach', 'Persikų spalva'), ('ivory', 'Dramblio kaulo spalva'), ('champagne', 'Šampano spalva'), ('rose_gold', 'Rožinis auksas'), ('bronze', 'Bronzinė'), ('blush', 'Rožinė'), ('cobalt_blue', 'Kobalto mėlyna'), ('emerald', 'Smaragdinė'), ('magenta', 'Violetinė'), ('fuchsia', 'Fuksijų spalva')], db_index=True, default=None, max_length=20, verbose_name='spalva'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sukurta'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, max_length=100000, verbose_name='aprašymas'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_available',
            field=models.BooleanField(db_index=True, default=False, verbose_name='yra prieinama'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False, verbose_name='parduodama'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='vardas'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='savininkas'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kaina'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.CharField(choices=[('XXXS / 30 / 2', 'XXXS / 30 / 2'), ('XXS / 32 / 4', 'XXS / 32 / 4'), ('XS / 34 / 6', 'XS / 34 / 6'), ('S / 36 / 8', 'S / 36 / 8'), ('M / 38 / 10', 'M / 38 / 10'), ('L / 40 / 12', 'L / 40 / 12'), ('XL / 42 / 14', 'XL / 42 / 14'), ('XXL / 44 / 16', 'XXL / 44 / 16'), ('XXXL / 46 / 18', 'XXXL / 46 / 18'), ('4XL / 48 / 20', '4XL / 48 / 20'), ('5XL / 50 / 22', '5XL / 50 / 22'), ('6XL / 52 / 24', '6XL / 52 / 24'), ('7XL / 54 / 26', '7XL / 54 / 26'), ('8XL / 56 / 28', '8XL / 56 / 28'), ('35', '35'), ('35.5', '35.5'), ('36', '36'), ('36.5', '36.5'), ('37', '37'), ('37.5', '37.5'), ('38', '38'), ('38.5', '38.5'), ('39', '39'), ('39.5', '39.5'), ('40', '40'), ('40.5', '40.5'), ('41', '41'), ('41.5', '41.5'), ('42', '42'), ('42.5', '42.5'), ('43', '43'), ('43.5', '43.5'), ('44', '44'), ('44.5', '44.5'), ('45', '45'), ('45.5', '45.5'), ('46', '46'), ('46.5', '46.5'), ('47', '47'), ('47.5', '47.5'), ('48', '48'), ('48.5', '48.5'), ('One Size', 'One Size'), ('Other', 'Other')], db_index=True, max_length=20, verbose_name='dydis'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='atnaujinta'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='vertė'),
        ),
        migrations.AlterField(
            model_name='listingreview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing', verbose_name='apžvelgtas skelbimas'),
        ),
        migrations.AlterField(
            model_name='listingreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='apžvalga pateikta'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='vardas'),
        ),
    ]
