# Generated by Django 5.0.2 on 2024-10-09 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_alter_brand_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingreview',
            options={'verbose_name': 'skelbimo atsiliepimas', 'verbose_name_plural': 'skelbimo atsiliepimai'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_available',
            field=models.BooleanField(db_index=True, default=False, verbose_name='prieinama'),
        ),
        migrations.AlterField(
            model_name='listingreview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing', verbose_name='atsiliepimas paliktas skelbimui'),
        ),
        migrations.AlterField(
            model_name='listingreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='atsiliepimas paliktas'),
        ),
    ]
