# Generated by Django 5.0.2 on 2024-10-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_alter_listingreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='sell_price'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='pavadinimas'),
        ),
    ]
