# Generated by Django 5.0.2 on 2024-10-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_tag_name_en_tag_name_lt_alter_listing_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='quality',
            field=models.CharField(choices=[('newwithtags', 'newwithtags'), ('newwithouttags', 'newwithouttags'), ('great', 'great'), ('good', 'good'), ('worn', 'worn')], default='good', max_length=20),
        ),
    ]
