# Generated by Django 5.0.2 on 2024-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_alter_listing_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(choices=[('en', [('black', 'Black'), ('white', 'White'), ('gray', 'Grey'), ('silver', 'Silver'), ('gold', 'Golden'), ('beige', 'Beige'), ('brown', 'Brown'), ('dark_blue', 'Dark Blue'), ('blue', 'Blue'), ('light_blue', 'Light Blue'), ('cyan', 'Blue'), ('green', 'Green'), ('khaki', 'Khaki'), ('yellow', 'Yellow'), ('mustard', 'Mustard'), ('orange', 'Orange'), ('coral', 'Coral'), ('red', 'Red'), ('burgundy', 'Burgundy'), ('light_pink', 'Light Pink'), ('pink', 'Pink'), ('bright_pink', 'Bright Pink'), ('purple', 'Purple'), ('lavender', 'Lavender'), ('mint', 'Mint'), ('turquoise', 'Turquoise'), ('maroon', 'Burgundy'), ('peach', 'Peach'), ('ivory', 'Ivory'), ('champagne', 'Champagne'), ('rose_gold', 'Rose Gold'), ('bronze', 'Bronze'), ('blush', 'Pink'), ('cobalt_blue', 'Cobalt Blue'), ('emerald', 'Emerald'), ('magenta', 'Purple'), ('fuchsia', 'Fuchsia')]), ('lt', [('black', 'Juoda'), ('white', 'Balta'), ('gray', 'Pilka'), ('silver', 'Sidabrinė'), ('gold', 'Auksinė'), ('beige', 'Smėlio'), ('brown', 'Ruda'), ('dark_blue', 'Tamsiai mėlyna'), ('blue', 'Mėlyna'), ('light_blue', 'Šviesiai mėlyna'), ('cyan', 'Žydra'), ('green', 'Žalia'), ('khaki', 'Chaki'), ('yellow', 'Geltona'), ('mustard', 'Garstyčių'), ('orange', 'Oranžinė'), ('coral', 'Koralinė'), ('red', 'Raudona'), ('burgundy', 'Bordo'), ('light_pink', 'Šviesiai rožinė'), ('pink', 'Rožinė'), ('bright_pink', 'Ryškiai rožinė'), ('purple', 'Violetinė'), ('lavender', 'Levandų'), ('mint', 'Mėtų'), ('turquoise', 'Turkio'), ('maroon', 'Bordo'), ('peach', 'Persikinė'), ('ivory', 'Dramblio kaulo'), ('champagne', 'Šampaninė'), ('rose_gold', 'Rožinis auksas'), ('bronze', 'Bronzinė'), ('blush', 'Rožinė'), ('cobalt_blue', 'Kobalto mėlyna'), ('emerald', 'Smaragdinė'), ('magenta', 'Purpurinė'), ('fuchsia', 'Fuksija')])], db_index=True, default=None, max_length=20, verbose_name='spalva'),
        ),
    ]
